### ISSUE TITLE
Inaccurate command

### ISSUE THREAD

**Issue by dkp** [datalad/datalad-binder#4]
Thanks for creating this Jupyter Notebook to teach datalad!  it is a very cool idea. 

I've run across a problem: The text claims  you can see how big the dataset would be if it were all downloaded:

It is tiny! But we can also find out how large the dataset would be if we had all of its contents with datalad 
status and the --annex flag. In total, there are more than 15GB of podcasts you have now access to:

`datalad status --annex`
2 annex'd files (13.9 MB recorded total size) nothing to save, working tree clean

Clearly, this does not work as advertised!

The correct command appears to be the following:
`datalad status -r --annex --untracked all`

238 annex'd files (15.5 GB recorded total size)
nothing to save, working tree clean

**Comment by jsheunis** [comment]
@dkp thanks for logging the issue, and sorry for the late response!

I've looked into the issue. Firstly, just to be sure we're working with the same notebook, can you share the link that you used to access it? The one I'm working with is the *Explore DataLad - an intro* Binder button, available from this repo: https://github.com/datalad/tutorials.

I've run the commands, the original one and the one you suggested, and both give me the same output:

![Screenshot 2022-03-14 at 16 04 51](https://user-images.githubusercontent.com/10141237/158201284-25ae9b82-0293-405c-93e7-f52a8926bf1a.png)

Do you think it's possible that your original `datalad status --annex` was run from a different directory, or at a different stage in the tutorial? E.g. if we run it for the original dataset created in the beginning of the tutorial, after the two pdf files were added to the dataset, it should show 2 annexed files as output.

**Comment by jsheunis** [comment]
Closing since no further interaction and problem seemed to be addressed.
